
name: onchain_heritage
description: A Web3 Flutter dApp to reveal pixel art via on-chain interactions
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^0.13.6
  web3dart: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/OnchainHeritage.abi.json
    - lib/assets/images/blocks/
