
name: onchain_heritage
description: OnchainHeritage is a fully on-chain interactive Web3 experience that transforms every wallet interaction into a meaningful contribution to a collective legacy. Each time a user interacts with the smart contract, they unlock a small part of a large pixel-art image. Once the community reaches 100,000 total interactions, the complete artwork is revealed, symbolizing the power of unity and on-chain participation. 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  get: ^4.6.6
  http: ^0.13.6
  web3dart: ^2.6.1

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  
flutter:
  uses-material-design: true
  assets:
    - assets/OnchainHeritage.abi.json
    - assets/images/
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"        # background same as your canvas splash
  image: "assets/bag_logo.png"
flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#1a1a1a"
    theme_color: "#9353D3"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#1a1a1a"
  adaptive_icon_foreground: "assets/images/logo.png"